---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - apt::default
  - name: centos-7.1
    run_list:
      - yum-epel::default
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private

suites:
  - name: languages_rust
    run_list: languages_rust::default
  - name: languages_nvm
    run_list: languages_nvm::default
  - name: languages_nodejs
    run_list: languages_nodejs::default
  - name: languages_rust_prefix
    run_list: languages_rust::prefix
  - name: languages_ruby
    run_list: languages_ruby::default
  - name: languages_ruby_prefix
    run_list: languages_ruby::prefix
