driver:
  name: vagrant
  provider: hyperv

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.7
    run_list: yum-epel::default
  - name: centos-7.1
    run_list: yum-epel::default
  - name: windows-server-2012r2-standard
    driver:
      #box: chef/windows-server-2012r2-standard
      box: mwrock/Windows2012R2
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private

suites:
  - name: languages_node
    run_list: languages_node::default
    excludes: windows-server-2012r2-standard
  - name: languages_ruby
    run_list: languages_ruby::default
  - name: languages_rust
    run_list: languages_rust::default
  - name: languages_erlang
    run_list: languages_erlang::default
    excludes: windows-server-2012r2-standard
  - name: devkit
    run_list: devkit::default
