sudo: required
distro: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

services:
  - docker

env:
  matrix:
    - CHEF_VERSION=12.1.0 LANGUAGE=erlang OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=node OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=ruby OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=rust OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=erlang OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=node OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=ruby OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=rust OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=erlang OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=node OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=ruby OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=rust OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=erlang OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=node OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=ruby OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=rust OS=centos-7

matrix:
  fast_finish: true

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - chef gem install chef-sugar
  # Ensure kitchen-docker is available for testing
  - chef gem install kitchen-docker
script:
  - chef --version
  - cookstyle --version
  - cookstyle
  - foodcritic --version
  - foodcritic . --exclude spec
  - rspec spec
  - kitchen --version
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml travis_wait 45 kitchen verify "languages-$LANGUAGE-$OS"
