name 'languages'
maintainer 'Chef Software Inc.'
maintainer_email 'releng@chef.io'
license 'Apache-2.0'
description 'Installs/Configures languages'
long_description 'Installs/Configures languages'
version '0.3.0'

source_url 'https://github.com/chef-cookbooks/languages'
issues_url 'https://github.com/chef-cookbooks/languages/issues'

depends 'build-essential'
depends 'chef-sugar'
depends 'homebrew'
depends 'remote_install'
