name 'languages'
maintainer 'Chef Software Inc.'
maintainer_email 'releng@chef.io'
license 'Apache 2.0'
description 'Installs/Configures languages'
long_description 'Installs/Configures languages'
version '0.1.4'

depends 'chef-sugar', '~> 3.1'
depends 'build-essential', '~> 2.2'
depends 'remote_install',  '~> 1.0'
